    #! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jul 01, 2018 01:37:03 PM

import cx_Oracle as c
import smtplib as s


try:
    from Tkinter import *

except ImportError:
    from tkinter import *

import tkinter
from tkinter import messagebox


import datetime as dt

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import employee_panel_support
import emp_allbills as abil


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    employee_panel_support.set_Tk_var()
    top = New_Toplevel (root)
    employee_panel_support.init(root, top)
    root.mainloop()

w=None

def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    employee_panel_support.set_Tk_var()
    top = New_Toplevel (w)
    employee_panel_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None

   

class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("600x450+478+236")
        top.title("Employee Panel")
        top.configure(background="#d9d9d9")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.02, rely=0.02, relheight=0.68, relwidth=0.98)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(width=585)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.02, rely=0.03, height=41, width=107)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Employee No''')
        self.Label1.configure(width=107)

        self.Label1_1 = Label(self.Frame1)
        self.Label1_1.place(relx=0.02, rely=0.16, height=41, width=74)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#d9d9d9")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''Bill No''')
        self.Label1_1.configure(width=74)

        self.Label1_2 = Label(self.Frame1)
        self.Label1_2.place(relx=0.02, rely=0.3, height=41, width=84)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#d9d9d9")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(foreground="#000000")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''Bill Type''')
        self.Label1_2.configure(width=84)

        self.Label1_3 = Label(self.Frame1)
        self.Label1_3.place(relx=0.038, rely=0.70, height=41, width=84)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#d9d9d9")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''Bill Amount''')

        self.Label1_41 = Label(self.Frame1)
        self.Label1_41.place(relx=0.03, rely=0.82, height=41, width=74)
        self.Label1_41.configure(activebackground="#f9f9f9")
        self.Label1_41.configure(activeforeground="black")
        self.Label1_41.configure(background="#d9d9d9")
        self.Label1_41.configure(disabledforeground="#a3a3a3")
        self.Label1_41.configure(foreground="#000000")
        self.Label1_41.configure(highlightbackground="#d9d9d9")
        self.Label1_41.configure(highlightcolor="black")
        self.Label1_41.configure(text='''Remarks''')
        self.Label1_41.configure(width=74)

        self.eno = Label(self.Frame1)
        self.eno.place(relx=0.26, rely=0.07,height=20, relwidth=0.28)
        self.eno.configure(activebackground="#f9f9f9")
        self.eno.configure(activeforeground="black")
        self.eno.configure(background="#d9d9d9")
        self.eno.configure(disabledforeground="#a3a3a3")
        self.eno.configure(foreground="#000000")
        self.eno.configure(highlightbackground="#d9d9d9")
        self.eno.configure(highlightcolor="black")
        self.eno.configure(text='''None''')
        self.eno.configure(width=74)

        f1=open("Data_Entry.txt","r")
        self.e_no=str(f1.read())
        self.eno.configure(text=self.e_no)

        self.bno = Entry(self.Frame1)
        self.bno.place(relx=0.26, rely=0.2,height=20, relwidth=0.28)
        self.bno.configure(background="white")
        self.bno.configure(disabledforeground="#a3a3a3")
        self.bno.configure(font="TkFixedFont")
        self.bno.configure(foreground="#000000")
        self.bno.configure(highlightbackground="#d9d9d9")
        self.bno.configure(highlightcolor="black")
        self.bno.configure(insertbackground="black")
        self.bno.configure(selectbackground="#c4c4c4")
        self.bno.configure(selectforeground="black")

        self.eno_12 = Entry(self.Frame1)
        self.eno_12.place(relx=0.26, rely=0.72,height=20, relwidth=0.28)
        self.eno_12.configure(background="white")
        self.eno_12.configure(disabledforeground="#a3a3a3")
        self.eno_12.configure(font="TkFixedFont")
        self.eno_12.configure(foreground="#000000")
        self.eno_12.configure(highlightbackground="#d9d9d9")
        self.eno_12.configure(highlightcolor="black")
        self.eno_12.configure(insertbackground="black")
        self.eno_12.configure(selectbackground="#c4c4c4")
        self.eno_12.configure(selectforeground="black")

        self.remarks = Entry(self.Frame1)
        self.remarks.place(relx=0.26, rely=0.85,height=20, relwidth=0.38)
        self.remarks.configure(background="white")
        self.remarks.configure(disabledforeground="#a3a3a3")
        self.remarks.configure(font="TkFixedFont")
        self.remarks.configure(foreground="#000000")
        self.remarks.configure(highlightbackground="#d9d9d9")
        self.remarks.configure(highlightcolor="black")
        self.remarks.configure(insertbackground="black")
        self.remarks.configure(selectbackground="#c4c4c4")
        self.remarks.configure(selectforeground="black")

        self.Label2_121 = Label(self.Frame1)
        self.Label2_121.place(relx=0.63, rely=0.08, height=35, width=114)
        self.Label2_121.configure(activebackground="#f9f9f9")
        self.Label2_121.configure(activeforeground="black")
        self.Label2_121.configure(background="#d9d9d9")
        self.Label2_121.configure(disabledforeground="#a3a3a3")
        self.Label2_121.configure(foreground="black")
        self.Label2_121.configure(highlightbackground="#d9d9d9")
        self.Label2_121.configure(highlightcolor="black")
        self.Label2_121.configure(text='''Last Login : ''')
        self.Label2_121.configure(width=114)

        self.Label2_12 = Label(self.Frame1)
        self.Label2_12.place(relx=0.78, rely=0.09, height=31, width=100)
        self.Label2_12.configure(activebackground="#f9f9f9")
        self.Label2_12.configure(activeforeground="black")
        self.Label2_12.configure(background="#d9d9d9")
        self.Label2_12.configure(disabledforeground="#a3a3a3")
        self.Label2_12.configure(foreground="black")
        self.Label2_12.configure(highlightbackground="#d9d9d9")
        self.Label2_12.configure(highlightcolor="black")
        self.Label2_12.configure(text='''NA''')
        self.Label2_12.configure(width=114)

        self.Message1 = Message(self.Frame1)
        self.Message1.place(relx=0.68, rely=0.35, relheight=0.6, relwidth=0.25)
        self.Message1.configure(background="#d9d9d9")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''To View Bill Status :
    
    1) Enter the Bill No
    2) Click View Bill Status



    To Submit Bill :
    
    1) Enter the details
    2) Click Submit''')
        self.Message1.configure(width=240)

        self.Label2 = Label(top)
        self.Label2.place(relx=0.038, rely=0.73, height=21, width=114)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Concerned Manager''')

        self.Label2_8 = Label(top)
        self.Label2_8.place(relx=0.035, rely=0.83, height=21, width=114)
        self.Label2_8.configure(activebackground="#f9f9f9")
        self.Label2_8.configure(activeforeground="black")
        self.Label2_8.configure(background="#d9d9d9")
        self.Label2_8.configure(disabledforeground="#a3a3a3")
        self.Label2_8.configure(foreground="#000000")
        self.Label2_8.configure(highlightbackground="#d9d9d9")
        self.Label2_8.configure(highlightcolor="black")
        self.Label2_8.configure(text='''Manager No''')

        self.Label2_9 = Label(top)
        self.Label2_9.place(relx=0.28, rely=0.73, height=21, width=114)
        self.Label2_9.configure(activebackground="#f9f9f9")
        self.Label2_9.configure(activeforeground="black")
        self.Label2_9.configure(background="#d9d9d9")
        self.Label2_9.configure(disabledforeground="#a3a3a3")
        self.Label2_9.configure(foreground="red")
        self.Label2_9.configure(highlightbackground="#d9d9d9")
        self.Label2_9.configure(highlightcolor="black")
        self.Label2_9.configure(text='''Select Bill Type First''')

        self.Label2_10 = Label(top)
        self.Label2_10.place(relx=0.28, rely=0.82, height=31, width=114)
        self.Label2_10.configure(activebackground="#f9f9f9")
        self.Label2_10.configure(activeforeground="black")
        self.Label2_10.configure(background="#d9d9d9")
        self.Label2_10.configure(disabledforeground="#a3a3a3")
        self.Label2_10.configure(foreground="red")
        self.Label2_10.configure(highlightbackground="#d9d9d9")
        self.Label2_10.configure(highlightcolor="black")
        self.Label2_10.configure(text='''Select Bill Type First''')
        self.Label2_10.configure(width=114)

        self.Label1_4 = Label(top)
        self.Label1_4.place(relx=0.035, rely=0.92, height=21, width=114)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#d9d9d9")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Bill Status''')

        self.Label1_3= Label(top)
        self.Label1_3.place(relx=0.28, rely=0.91, height=31, width=114)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#d9d9d9")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(foreground="blue")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''Pending''')
        self.Label1_3.configure(width=84)

        conn = c.connect("system/2824@localhost/xe")
        cur=conn.cursor()
        
        data3=cur.execute("select * from employee where eno='"+self.e_no+"'")
        self.last=''
        for row3 in data3:
            self.last=row3[4]

        self.Label2_12.configure(text=self.last)

        curr=dt.datetime.now()
        cur.execute("update employee set last='"+str(curr.strftime("%d-%m-%y %H:%M"))+"'")
        conn.commit()
        conn.close()
        
        self.btnbtype1 = Button(self.Frame1)
        self.btnbtype1.place(relx=0.26, rely=0.33, relheight=0.08
                , relwidth=0.07)
        self.btnbtype1.configure(activebackground="#d9d9d9")
        self.btnbtype1.configure(activeforeground="#000000")
        self.btnbtype1.configure(background="#d9d9d9")
        self.btnbtype1.configure(disabledforeground="#a3a3a3")
        self.btnbtype1.configure(foreground="#000000")
        self.btnbtype1.configure(highlightbackground="#d9d9d9")
        self.btnbtype1.configure(highlightcolor="black")
        self.btnbtype1.configure(justify=LEFT)
        self.btnbtype1.configure(text='''b1''')
        self.btnbtype1.configure(command=lambda:self.get_selection("b1"))

        self.btnbtype2 = Button(self.Frame1)
        self.btnbtype2.place(relx=0.26, rely=0.46, relheight=0.08
                , relwidth=0.07)
        self.btnbtype2.configure(activebackground="#d9d9d9")
        self.btnbtype2.configure(activeforeground="#000000")
        self.btnbtype2.configure(background="#d9d9d9")
        self.btnbtype2.configure(disabledforeground="#a3a3a3")
        self.btnbtype2.configure(foreground="#000000")
        self.btnbtype2.configure(highlightbackground="#d9d9d9")
        self.btnbtype2.configure(highlightcolor="black")
        self.btnbtype2.configure(justify=LEFT)
        self.btnbtype2.configure(text='''b2''')
        self.btnbtype2.configure(command=lambda:self.get_selection("b2"))

        self.btnbtype3 = Button(self.Frame1)
        self.btnbtype3.place(relx=0.26, rely=0.59, relheight=0.08
                , relwidth=0.07)
        self.btnbtype3.configure(activebackground="#d9d9d9")
        self.btnbtype3.configure(activeforeground="#000000")
        self.btnbtype3.configure(background="#d9d9d9")
        self.btnbtype3.configure(disabledforeground="#a3a3a3")
        self.btnbtype3.configure(foreground="#000000")
        self.btnbtype3.configure(highlightbackground="#d9d9d9")
        self.btnbtype3.configure(highlightcolor="black")
        self.btnbtype3.configure(justify=LEFT)
        self.btnbtype3.configure(text='''b3''')
        self.btnbtype3.configure(command=lambda:self.get_selection("b3"))        

        self.submit = Button(top)
        self.submit.place(relx=0.78, rely=0.87, height=34, width=97)
        self.submit.configure(activebackground="#d9d9d9")
        self.submit.configure(activeforeground="#000000")
        self.submit.configure(background="#d9d9d9")
        self.submit.configure(disabledforeground="#a3a3a3")
        self.submit.configure(foreground="#000000")
        self.submit.configure(highlightbackground="#d9d9d9")
        self.submit.configure(highlightcolor="black")
        self.submit.configure(pady="0")
        self.submit.configure(text='''Submit''')
        self.submit.configure(width=97)
        self.submit.configure(command=self.submitdata)

        self.view = Button(top)
        self.view.place(relx=0.78, rely=0.76, height=34, width=97)
        self.view.configure(activebackground="#d9d9d9")
        self.view.configure(activeforeground="#000000")
        self.view.configure(background="#d9d9d9")
        self.view.configure(disabledforeground="#a3a3a3")
        self.view.configure(foreground="#000000")
        self.view.configure(highlightbackground="#d9d9d9")
        self.view.configure(highlightcolor="black")
        self.view.configure(pady="0")
        self.view.configure(text='''View Bill Status''')
        self.view.configure(command=self.viewdata)

        self.viewall = Button(top)
        self.viewall.place(relx=0.58, rely=0.76, height=34, width=110)
        self.viewall.configure(activebackground="#d9d9d9")
        self.viewall.configure(activeforeground="#000000")
        self.viewall.configure(background="#d9d9d9")
        self.viewall.configure(disabledforeground="#a3a3a3")
        self.viewall.configure(foreground="#000000")
        self.viewall.configure(highlightbackground="#d9d9d9")
        self.viewall.configure(highlightcolor="black")
        self.viewall.configure(pady="0")
        self.viewall.configure(text='''View All Submitted''')
        self.viewall.configure(command=self.viewalldata)

        self.b_type="b1"
        self.m_no="m1"

    def get_selection(self,pos):
        self.b_type=pos
        print(self.b_type)
        if self.b_type=='b1':
            self.btnbtype1.configure(background="green")
            self.btnbtype2.configure(background="#d9d9d9")
            self.btnbtype3.configure(background="#d9d9d9")

            self.m_no='m1'
            self.Label2_9.configure(text=''' Manager 1 ''')
            self.Label2_10.configure(text=''' m1 ''')
            
        elif self.b_type=='b2':
            self.btnbtype1.configure(background="#d9d9d9")
            self.btnbtype2.configure(background="green")
            self.btnbtype3.configure(background="#d9d9d9")

            self.m_no='m2'
            self.Label2_9.configure(text=''' Manager 2 ''')
            self.Label2_10.configure(text=''' m2 ''')
        elif self.b_type=='b3':
            self.btnbtype1.configure(background="#d9d9d9")
            self.btnbtype2.configure(background="#d9d9d9")
            self.btnbtype3.configure(background="green")

            self.m_no='m3'
            self.Label2_9.configure(text=''' Manager 3 ''')
            self.Label2_10.configure(text=''' m3 ''')

        self.Label2_9.configure(fg='green')
        self.Label2_10.configure(fg='green')

    def viewdata(self):
        self.b_no=self.bno.get()
        if(len(self.b_no)>0):

            conn = c.connect("system/2824@localhost/xe")
            cur=conn.cursor()
                
            data=cur.execute("select * from requests where bill_no='"+self.b_no+"'")
            r=data.fetchone()
            if(r==None):
                    messagebox.showinfo('Error','Bill No. '+self.b_no+' not found!')
            else:
                data=cur.execute("select * from requests where bill_no='"+self.b_no+"'")
                for row in data:
                    self.e_nov=row[2]
                    self.m_no=row[1]
                    data2=cur.execute("select * from manager where mno='"+self.m_no+"'")
                    for row2 in data2:
                        self.m_name=row2[1]

                    self.b_type=row[3]
                    self.b_amt=row[4]
                    self.b_stat=row[5]
                    self.b_remarks=row[6]
                    self.remarks.delete(0,END)
                    self.remarks.insert(0,self.b_remarks)

                    self.get_selection(self.b_type)

                    self.eno.configure(text=self.e_nov)

                    self.eno_12.delete(0,END)
                    self.eno_12.insert(0,self.b_amt)

                    self.Label1_3.configure(text=self.b_stat)
                    if(self.b_stat=='Approved'):
                        self.Label1_3.configure(fg="green")
                    elif(self.b_stat=='Rejected'):
                        self.Label1_3.configure(fg="red")
                    else:
                        self.Label1_3.configure(fg="blue")
                        
                    self.Label2_9.configure(text=self.m_name)
                    self.Label2_9.configure(fg="green")

                    self.Label2_10.configure(text=self.m_no)
                    self.Label2_10.configure(fg="green")

            conn.close()
        else:
            messagebox.showinfo('Error','Bill No. not specified!')

    def viewalldata(self):
        f1=open("show_bills.txt","w+")
        f1.write(self.e_no)
        f1.close()
        abil.vp_start_gui()
                    
    def submitdata(self):
        self.msg=messagebox.askokcancel("Submit","Would you like to save the data?")
        
        if(self.msg):
            self.b_no=self.bno.get()
            self.b_amt=self.eno_12.get()
            self.b_remarks=self.remarks.get()
            
            if(len(self.m_no)>0 and len(self.b_no)>0 and len(self.b_amt)>0 and len(self.b_type)>0 and len(self.b_remarks)>0):

                conn = c.connect("system/2824@localhost/xe")
                cur=conn.cursor()
                cur.execute("select * from requests where bill_no='"+self.b_no+"'")
                cnt=cur.fetchone()
                print(str(cnt))
                
                if(str(cnt)=='None'):
                    print(self.b_no+' '+self.m_no+' '+self.e_no+' '+self.b_type+' '+self.b_amt+' '+self.b_remarks)
                    cur.execute("Insert into requests values(:1,:2,:3,:4,:5,:6,:7)",(self.b_no,self.m_no,self.e_no,self.b_type,self.b_amt,'Pending',self.b_remarks))
                    conn.commit()
                    conn.close()
                    messagebox.showinfo('Successfull','Saved')

                    server=s.SMTP('smtp.gmail.com',587)
                    server.ehlo()
                    server.starttls()

                    server.login("budget.approval.system.project@gmail.com",'Budget@python07')

                    text='\nYour submission of Bill No. : '+self.b_no+' has been received by us and will be processed shortly.\n\nEmployee No. : '+self.e_no+'\nManager No. : '+self.m_no+'\nBill No. : '+self.b_no+'\nBill Amount : '+self.b_amt+'\nBill Remarks : '+self.b_remarks+'\nBill Status : Pending';
                    
                    msg = """From: %s\nTo: %s\nSubject: %s\n\n%s""" %('budget.approval.system.project@gmail.com', ",", 'Bill Submission', text)

                    server.sendmail("budget.approval.system.project@gmail.com",'16bit159@nirmauni.ac.in',msg)
                    server.quit()


                else:
                    messagebox.showinfo('Error','Bill No. '+self.b_no+' already processed!')    

            else:
                    messagebox.showinfo('Error','Data not filled!')    


if __name__ == '__main__':
    vp_start_gui()



